version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/packages/gatsby-plugin-intl'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: '/packages/gatsby-theme-intl'
    schedule:
      interval: 'daily'
