version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm i
      - run: npm run test

  publish:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm run bootstrap
      - run: npm run publish

workflows:
  version: 2
  pipeline:
    jobs:
      - test
      - publish:
          filters:
            branches:
              only: master
