version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:
  audit:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm audit

  test:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm i
      - run: npm run test

workflows:
  version: 2
  pipeline:
    jobs:
      - audit
      - test
