version: 2.1

orbs:
  node: circleci/node@1.1.6

commands:
  setup:
    steps:
      - checkout
      - run: npm i
      - run: npm run bootstrap

jobs:
  test:
    executor:
      name: node/default
    steps:
      - setup
      - run: npm run test

  publish:
    executor:
      name: node/default
    steps:
      - setup
      - run: git config user.name "3nvi"
      - run: git config user.email "agg.arvanitakis@gmail.com"
      - run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
      - run: npm run version
      - run: npm run publish -- --yes

workflows:
  version: 2
  pipeline:
    jobs:
      - test
      - publish:
          filters:
            branches:
              only: master
