version: 2.1

jobs:
  audit:
    steps:
      - checkout
      - run: npm audit

  test:
    steps:
      - checkout
      - run: npm i
      - run: npm run test

workflows:
  version: 2
  pipeline:
    jobs:
      - audit
      - test
